{/* <div className="mt-4">
  <video
    id={`video-${index}`}
    className="video-js w-full rounded-md"
    controls
    preload="auto"
    data-setup="{}"
  >
    <source src={episode.streaming} type="video/mp4" />
  </video>
</div>; */}



        {/* <nav className="mb-4 flex justify-center gap-6">
          <a href="/about" className="hover:text-white">About</a>
          <a href="/contact" className="hover:text-white">Contact</a>
          <a href="/terms" className="hover:text-white">Terms of Service</a>
          <a href="/privacy" className="hover:text-white">Privacy Policy</a>
        </nav> */}

        {/* <div className="flex justify-center gap-4 mb-4">
          <a href="#" className="hover:text-white text-xl">
            <FontAwesomeIcon icon={faFacebook} size="3x"/>
          </a>
          <a href="#" className="hover:text-white text-xl">
          <FontAwesomeIcon icon={faTwitter} size="3x"/>
          </a>
          <a href="#" className="hover:text-white text-xl">
          <FontAwesomeIcon icon={faInstagram} size="3x"/>
          </a>
        </div> */}

        {/* <nav className="mb-4 flex justify-center gap-6">
          <a href="/about" className="hover:text-white">About</a>
          <a href="/contact" className="hover:text-white">Contact</a>
          <a href="/terms" className="hover:text-white">Terms of Service</a>
          <a href="/privacy" className="hover:text-white">Privacy Policy</a>
        </nav> */}

        {/* <div className="flex justify-center gap-4 mb-4">
          <a href="#" className="hover:text-white text-xl">
            <FontAwesomeIcon icon={faFacebook} size="3x"/>
          </a>
          <a href="#" className="hover:text-white text-xl">
          <FontAwesomeIcon icon={faTwitter} size="3x"/>
          </a>
          <a href="#" className="hover:text-white text-xl">
          <FontAwesomeIcon icon={faInstagram} size="3x"/>
          </a>
        </div> */}
